import type {
  ComponentInfo,
  ElementInfo,
  GeneratedTest,
  TestGeneratorOptions,
} from '../../types';
import { basename, dirname, join } from 'path';

const DEFAULT_OPTIONS: TestGeneratorOptions = {
  includeVisibility: true,
  includeInteractions: true,
  includeNavigation: false, // Not applicable for component tests
  includeForms: true,
  includeA11y: false,
  addTodos: true,
};

/**
 * Generate component test file using @ux.qa/frontmock
 */
export function generateComponentTest(
  component: ComponentInfo,
  options: Partial<TestGeneratorOptions> = {}
): GeneratedTest {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const tests: string[] = [];
  let testCount = 0;

  // Group elements by type
  const buttons = component.elements.filter(e => e.type === 'button');
  const inputs = component.elements.filter(e => ['input', 'textarea', 'select'].includes(e.type));
  const checkboxes = component.elements.filter(e => e.type === 'checkbox');
  const radios = component.elements.filter(e => e.type === 'radio');
  const forms = component.elements.filter(e => e.type === 'form');

  // Generate visibility/rendering test
  if (opts.includeVisibility && component.elements.length > 0) {
    tests.push(generateRenderTest(component));
    testCount++;
  }

  // Generate button click tests
  if (opts.includeInteractions && buttons.length > 0) {
    buttons.forEach((btn) => {
      tests.push(generateButtonClickTest(btn, opts.addTodos, component.name));
      testCount++;
    });
  }

  // Generate input tests
  if (opts.includeInteractions && inputs.length > 0 && forms.length === 0) {
    inputs.forEach((input) => {
      tests.push(generateInputChangeTest(input, opts.addTodos, component.name));
      testCount++;
    });
  }

  // Generate form tests
  if (opts.includeForms && forms.length > 0) {
    forms.forEach((form, index) => {
      tests.push(generateFormSubmitTest(form, inputs, index, opts.addTodos, component.name));
      testCount++;
    });
  }

  // Generate checkbox tests
  if (opts.includeInteractions && checkboxes.length > 0) {
    checkboxes.forEach((cb) => {
      tests.push(generateCheckboxTest(cb, opts.addTodos, component.name));
      testCount++;
    });
  }

  // Generate radio tests
  if (opts.includeInteractions && radios.length > 0) {
    radios.forEach((radio) => {
      tests.push(generateRadioTest(radio, opts.addTodos, component.name));
      testCount++;
    });
  }

  // Generate a11y test
  if (opts.includeA11y) {
    tests.push(generateA11yTest(component));
    testCount++;
  }

  const content = generateFullTestFile(component, tests);
  const fileName = `${toKebabCase(component.name)}.test.tsx`;
  const testDir = dirname(component.filePath).replace('/src/', '/tests/');

  return {
    filePath: join(testDir, fileName),
    content,
    componentName: component.name,
    testCount,
  };
}

function generateFullTestFile(
  component: ComponentInfo,
  tests: string[]
): string {
  // Extract component path for import
  const componentPath = component.filePath
    .replace(/\.(tsx|jsx)$/, '')
    .replace(/^src\//, '../');

  return `import { t } from '@ux.qa/frontmock';
import { ${component.name} } from '${componentPath}';

const { describe, it, expect, render, screen, userEvent } = t;

/**
 * Component tests for ${component.name}
 * Generated by @ux.qa/scanner
 *
 * Review and customize these tests before committing.
 */
describe('${component.name}', () => {
${tests.join('\n\n')}
});
`;
}

function generateRenderTest(component: ComponentInfo): string {
  const elementsWithTestId = component.elements.filter(e => e.testId);

  if (elementsWithTestId.length === 0) {
    // No test IDs - suggest adding them
    const suggestions = component.elements
      .slice(0, 5)
      .map(e => `  // Add data-testid="${e.suggestedTestId}" to ${e.type} at line ${e.line}`)
      .join('\n');

    return `  it('renders ${component.name}', () => {
    render(<${component.name} />);

    // TODO: Add data-testid attributes to elements for better test stability
${suggestions}

    // Example assertions (update selectors):
    // expect(screen.getByTestId('example')).toBeInTheDocument();
  });`;
  }

  const assertions = elementsWithTestId
    .map(e => `    expect(screen.getByTestId('${e.testId}')).toBeInTheDocument();`)
    .join('\n');

  return `  it('renders ${component.name}', () => {
    render(<${component.name} />);

${assertions}
  });`;
}

function generateButtonClickTest(element: ElementInfo, addTodos: boolean, componentName: string): string {
  const selector = element.testId || element.suggestedTestId;
  const label = element.label || element.testId || 'button';
  const todo = addTodos ? '\n    // TODO: Add assertion for expected behavior after click' : '';

  return `  it('handles ${label} click', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);

    const button = screen.getByTestId('${selector}');
    await user.click(button);${todo}
  });`;
}

function generateInputChangeTest(element: ElementInfo, addTodos: boolean, componentName: string): string {
  const selector = element.testId || element.suggestedTestId;
  const label = element.label || element.testId || 'input';
  const value = getTestValue(element);
  const todo = addTodos ? '\n    // TODO: Add assertion for input change effect' : '';

  return `  it('accepts input in ${label}', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);

    const input = screen.getByTestId('${selector}');
    await user.type(input, '${value}');

    expect(input).toHaveValue('${value}');${todo}
  });`;
}

function generateFormSubmitTest(
  form: ElementInfo,
  inputs: ElementInfo[],
  index: number,
  addTodos: boolean,
  componentName: string
): string {
  const fillStatements = inputs
    .map((input) => {
      const inputSelector = input.testId || input.suggestedTestId;
      const value = getTestValue(input);
      return `    await user.type(screen.getByTestId('${inputSelector}'), '${value}');`;
    })
    .join('\n');

  const formLabel = form.testId || `form${index > 0 ? ` ${index + 1}` : ''}`;
  const todo = addTodos ? '\n    // TODO: Add assertion for form submission result' : '';

  return `  it('submits ${formLabel}', async () => {
    const user = userEvent.setup();
    const onSubmit = vi.fn((e) => e.preventDefault());
    render(<${componentName} onSubmit={onSubmit} />);

${fillStatements || '    // TODO: Fill form fields'}

    const submitButton = screen.getByRole('button', { name: /submit/i });
    await user.click(submitButton);${todo}
  });`;
}

function generateCheckboxTest(element: ElementInfo, addTodos: boolean, componentName: string): string {
  const selector = element.testId || element.suggestedTestId;
  const label = element.label || element.testId || 'checkbox';
  const todo = addTodos ? '\n    // TODO: Add assertion for checkbox state change effect' : '';

  return `  it('toggles ${label} checkbox', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);

    const checkbox = screen.getByTestId('${selector}');

    // Check
    await user.click(checkbox);
    expect(checkbox).toBeChecked();

    // Uncheck
    await user.click(checkbox);
    expect(checkbox).not.toBeChecked();${todo}
  });`;
}

function generateRadioTest(element: ElementInfo, addTodos: boolean, componentName: string): string {
  const selector = element.testId || element.suggestedTestId;
  const label = element.label || element.testId || 'radio';
  const todo = addTodos ? '\n    // TODO: Add assertion for radio selection effect' : '';

  return `  it('selects ${label} radio', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);

    const radio = screen.getByTestId('${selector}');
    await user.click(radio);

    expect(radio).toBeChecked();${todo}
  });`;
}

function generateA11yTest(component: ComponentInfo): string {
  return `  it('meets accessibility standards', () => {
    const { container } = render(<${component.name} />);

    // Basic a11y checks:
    // - All images have alt text
    const images = container.querySelectorAll('img:not([alt])');
    expect(images).toHaveLength(0);

    // - All form inputs have labels
    const inputs = container.querySelectorAll('input:not([aria-label]):not([id])');
    expect(inputs).toHaveLength(0);

    // TODO: Add axe-core for comprehensive a11y testing
    // import { axe } from 'jest-axe';
    // const results = await axe(container);
    // expect(results).toHaveNoViolations();
  });`;
}

function getTestValue(element: ElementInfo): string {
  const inputType = element.inputType || 'text';

  switch (inputType) {
    case 'email':
      return 'test@example.com';
    case 'password':
      return 'TestPassword123!';
    case 'tel':
      return '+1234567890';
    case 'url':
      return 'https://example.com';
    case 'number':
      return '42';
    case 'date':
      return '2024-01-01';
    default:
      return 'Test value';
  }
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}
